repos:
  - repo: local
    hooks:
      - id: tests
        name: tests
        entry: make test
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
